#Set directory paths
ROOT_DIR=$(shell git rev-parse --show-toplevel)
TOOLS_DIR=$(ROOT_DIR)/.tools
LETS_PARTY := $(ROOT_DIR)/bin/lets-party

#Set tool-paths for easier access
LINT := $(TOOLS_DIR)/golangci-lint

# Env vars
GO_ENV=$(shell CGO_ENABLED=0)

# Versioning
GO_VERSION=1.21
GOLINT_VERSION=v1.57.2
