name: Build and Publish Container Image

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check current branch
        if: github.ref != 'refs/heads/main'
        run: exit 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/lets-party:latest \
            .
          docker buildx stop --name github-builder

      - name: Clean up
        run: docker buildx rm --all --force
